/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.TelaInternal;

import br.com.DAO.CursoDAO;
import br.com.DAO.DisciplinaDAO;
import br.com.DAO.QuestaoDAO;
import br.com.JavaBean.Curso;
import br.com.JavaBean.Disciplina;
import br.com.JavaBean.Pessoa;
import br.com.JavaBean.Questao;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author manoel
 */
public class JICadastroQT extends javax.swing.JInternalFrame {

    CursoDAO daoCurso = new CursoDAO();
    DisciplinaDAO daoDisciplina = new DisciplinaDAO();
    List<Curso> listaCurso = daoCurso.consultarTodos();
    List<Disciplina> listaDisciplina = daoDisciplina.consultarTodos();
    int quantPer = 0;
    Pessoa user = null;
    
    public JICadastroQT(Pessoa pessoa) {
        initComponents();
        user = pessoa;
        
        quantPer = listaCurso.get(0).getQuantPeriodo() ;
        
        for (int i = 0; i < quantPer; i++) {
            cbPeriodo.addItem(""+(i+1));
        }
        
        for (int i = 0; i < listaCurso.size(); i++) {
           cbCurso.addItem(listaCurso.get(i).getNome());  
        }
        
        for (int i = 0; i < listaDisciplina.size(); i++) {
            cbDisciplina.addItem(listaDisciplina.get(i).getNome());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlter1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taEnunciado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAlter2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taAlter3 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taAlter4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        taAlter5 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taAssunto = new javax.swing.JTextArea();
        btExcluir = new javax.swing.JButton();
        chbCorreta1 = new javax.swing.JCheckBox();
        chbCorreta4 = new javax.swing.JCheckBox();
        chbCorreta2 = new javax.swing.JCheckBox();
        chbCorreta5 = new javax.swing.JCheckBox();
        chbCorreta3 = new javax.swing.JCheckBox();
        pn1 = new javax.swing.JPanel();
        cbCurso = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbGrauDificul = new javax.swing.JComboBox<>();
        cbPeriodo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbDisciplina = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de Questões");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 20)); // NOI18N
        jLabel1.setText("Enunciado: ");

        taAlter1.setColumns(20);
        taAlter1.setLineWrap(true);
        taAlter1.setRows(5);
        taAlter1.setWrapStyleWord(true);
        taAlter1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        jScrollPane1.setViewportView(taAlter1);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel2.setText("Alternativas:");

        jLabel3.setText("a)");

        taEnunciado.setColumns(20);
        taEnunciado.setLineWrap(true);
        taEnunciado.setRows(5);
        taEnunciado.setWrapStyleWord(true);
        taEnunciado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        taEnunciado.setPreferredSize(new java.awt.Dimension(125, 400));
        jScrollPane2.setViewportView(taEnunciado);

        jLabel4.setText("b)");

        taAlter2.setColumns(20);
        taAlter2.setLineWrap(true);
        taAlter2.setRows(5);
        taAlter2.setWrapStyleWord(true);
        taAlter2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        jScrollPane3.setViewportView(taAlter2);

        jLabel5.setText("c)");

        taAlter3.setColumns(20);
        taAlter3.setLineWrap(true);
        taAlter3.setRows(5);
        taAlter3.setWrapStyleWord(true);
        taAlter3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        jScrollPane4.setViewportView(taAlter3);

        jLabel6.setText("d)");

        taAlter4.setColumns(20);
        taAlter4.setLineWrap(true);
        taAlter4.setRows(5);
        taAlter4.setWrapStyleWord(true);
        taAlter4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        jScrollPane5.setViewportView(taAlter4);

        taAlter5.setColumns(20);
        taAlter5.setLineWrap(true);
        taAlter5.setRows(5);
        taAlter5.setWrapStyleWord(true);
        taAlter5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        jScrollPane6.setViewportView(taAlter5);

        jLabel7.setText("e)");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/btSalvar.png"))); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.setPreferredSize(new java.awt.Dimension(149, 60));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/borracha-limpar.gif"))); // NOI18N
        btLimpar.setText("LIMPAR");
        btLimpar.setPreferredSize(new java.awt.Dimension(149, 60));
        btLimpar.setRolloverEnabled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/cancel.gif"))); // NOI18N
        btCancel.setText("CANCELAR");
        btCancel.setMaximumSize(new java.awt.Dimension(144, 36));
        btCancel.setPreferredSize(new java.awt.Dimension(149, 60));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel8.setText("Assunto: ");

        taAssunto.setColumns(20);
        taAssunto.setLineWrap(true);
        taAssunto.setRows(5);
        taAssunto.setWrapStyleWord(true);
        taAssunto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(66, 61, 128), null));
        jScrollPane7.setViewportView(taAssunto);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/delete.png"))); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.setPreferredSize(new java.awt.Dimension(149, 60));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        chbCorreta1.setText("Correta");
        chbCorreta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCorreta1ActionPerformed(evt);
            }
        });

        chbCorreta4.setText("Correta");
        chbCorreta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCorreta4ActionPerformed(evt);
            }
        });

        chbCorreta2.setText("Correta");
        chbCorreta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCorreta2ActionPerformed(evt);
            }
        });

        chbCorreta5.setText("Correta");
        chbCorreta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCorreta5ActionPerformed(evt);
            }
        });

        chbCorreta3.setText("Correta");
        chbCorreta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCorreta3ActionPerformed(evt);
            }
        });

        pn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });

        jLabel9.setText("Curso: ");

        jLabel10.setText("<html>Grau de <br>Dificuldade:");

        cbGrauDificul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixo", "Medio", "Alto" }));

        jLabel11.setText("Período: ");

        jLabel12.setText("Disciplina:");

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn1Layout.createSequentialGroup()
                        .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGrauDificul, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGrauDificul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(chbCorreta1))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(chbCorreta2))
                                    .addComponent(jLabel1))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(chbCorreta4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(chbCorreta5))
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(chbCorreta3))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chbCorreta4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(chbCorreta1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(chbCorreta2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(chbCorreta5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(chbCorreta3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
       
       taEnunciado.setText("");
       taAlter1.setText("");
       taAlter2.setText("");
       taAlter3.setText("");
       taAlter4.setText("");
       taAlter5.setText("");
       taAssunto.setText("");
       
       cbCurso.setSelectedIndex(0);
       cbGrauDificul.setSelectedIndex(0);
       cbPeriodo.setSelectedIndex(0);
       
       chbCorreta1.setSelected(false);
       chbCorreta2.setSelected(false);
       chbCorreta3.setSelected(false);
       chbCorreta4.setSelected(false);
       chbCorreta5.setSelected(false);
       
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Questao q = new Questao();
        q.setEnunciado(taEnunciado.getText().toString());
        q.setGrauDificuldade(cbGrauDificul.getSelectedItem().toString());
        q.setAssunto(taAssunto.getText().toString());
        q.setPessoa(user);
        q.setResposta(corretaSelecionada());
        Curso cursoSelecionado = null;
        Disciplina disciplinaSelecionada = null;
        
        // pegar curso selecionado
        for (int i = 0; i < listaCurso.size(); i++) {
            if(listaCurso.get(i).getNome().equals(cbCurso.getSelectedItem().toString())){
                cursoSelecionado = listaCurso.get(i);
                q.setCurso(cursoSelecionado);
            }
        }
        
        // pegar disciplina selecionada
        for (int i = 0; i < listaDisciplina.size(); i++) {
            if(listaDisciplina.get(i).getNome().equals(cbDisciplina.getSelectedItem().toString())){
                disciplinaSelecionada = listaDisciplina.get(i);
                q.setDisciplina(disciplinaSelecionada);
            }
        }
        
        
        QuestaoDAO dao = new QuestaoDAO();
        dao.salvar(q);
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed
        cbPeriodo.removeAllItems();
        for(int i = 0; i < listaCurso.size(); i++){
            if(listaCurso.get(i).getNome().equals(cbCurso.getSelectedItem().toString())){
                quantPer = listaCurso.get(i).getQuantPeriodo();
            }
        }
        
        for(int j = 0; j < quantPer; j++){
            cbPeriodo.addItem(""+(j+1));
        }
    }//GEN-LAST:event_cbCursoActionPerformed

    // Resposta A Selecionada
    private void chbCorreta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCorreta1ActionPerformed
        chbCorreta2.setSelected(false);
        chbCorreta3.setSelected(false);
        chbCorreta4.setSelected(false);
        chbCorreta5.setSelected(false);
    }//GEN-LAST:event_chbCorreta1ActionPerformed

    private void chbCorreta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCorreta2ActionPerformed
        chbCorreta1.setSelected(false);
        chbCorreta3.setSelected(false);
        chbCorreta4.setSelected(false);
        chbCorreta5.setSelected(false);
    }//GEN-LAST:event_chbCorreta2ActionPerformed

    private void chbCorreta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCorreta3ActionPerformed
        chbCorreta1.setSelected(false);
        chbCorreta2.setSelected(false);
        chbCorreta4.setSelected(false);
        chbCorreta5.setSelected(false);
    }//GEN-LAST:event_chbCorreta3ActionPerformed

    private void chbCorreta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCorreta4ActionPerformed
        chbCorreta1.setSelected(false);
        chbCorreta2.setSelected(false);
        chbCorreta3.setSelected(false);
        chbCorreta5.setSelected(false);
    }//GEN-LAST:event_chbCorreta4ActionPerformed

    private void chbCorreta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCorreta5ActionPerformed
        chbCorreta1.setSelected(false);
        chbCorreta2.setSelected(false);
        chbCorreta3.setSelected(false);
        chbCorreta4.setSelected(false);
    }//GEN-LAST:event_chbCorreta5ActionPerformed

    public int corretaSelecionada(){
        int resposta = -1;
        
        if(chbCorreta1.isSelected()){
            resposta = 0;
        }
        
        if(chbCorreta2.isSelected()){
            resposta = 1;
        }
        
        if(chbCorreta3.isSelected()){
            resposta = 2;
        }
        
        if(chbCorreta4.isSelected()){
            resposta = 3;
        }
        
        if(chbCorreta5.isSelected()){
            resposta = 4;
        }
        
        return resposta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbDisciplina;
    private javax.swing.JComboBox<String> cbGrauDificul;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JCheckBox chbCorreta1;
    private javax.swing.JCheckBox chbCorreta2;
    private javax.swing.JCheckBox chbCorreta3;
    private javax.swing.JCheckBox chbCorreta4;
    private javax.swing.JCheckBox chbCorreta5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pn1;
    private javax.swing.JTextArea taAlter1;
    private javax.swing.JTextArea taAlter2;
    private javax.swing.JTextArea taAlter3;
    private javax.swing.JTextArea taAlter4;
    private javax.swing.JTextArea taAlter5;
    private javax.swing.JTextArea taAssunto;
    private javax.swing.JTextArea taEnunciado;
    // End of variables declaration//GEN-END:variables
}
