package br.com.TelasPrincipais;

import br.com.TelaInternal.JIBuscaPessoa;
import br.com.TelaInternal.JIBuscaQT;
import br.com.TelaInternal.JICadCurso;
import br.com.TelaInternal.JICadDisciplina;
import br.com.TelaInternal.JICadPessoa;
import br.com.TelaInternal.JICadastroQT;
import javax.swing.JOptionPane;

/**
 * @author manoel
 */
public class TPrincipal extends javax.swing.JFrame {
    
    public TPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JDesktopPane();
        bmPrincipal = new javax.swing.JMenuBar();
        jmCad = new javax.swing.JMenu();
        jmiCadDisciplina = new javax.swing.JMenuItem();
        jmiCadCurso = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmPessoa = new javax.swing.JMenu();
        jmiConsultarPess = new javax.swing.JMenuItem();
        jmiCadPess = new javax.swing.JMenuItem();
        jmQT = new javax.swing.JMenu();
        jmiConsulQT = new javax.swing.JMenuItem();
        jmiCadQT = new javax.swing.JMenuItem();
        jmAvaliacao = new javax.swing.JMenu();
        jmiConsulAval = new javax.swing.JMenuItem();
        jmiMontarAval = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipal.setOpaque(false);

        bmPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jmCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/cadastro2.png"))); // NOI18N
        jmCad.setText("Cadastro");

        jmiCadDisciplina.setText("<html>Cadastrar<br/>Disciplina");
        jmiCadDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadDisciplinaActionPerformed(evt);
            }
        });
        jmCad.add(jmiCadDisciplina);

        jmiCadCurso.setText("<html>Cadastrar<br/> Curso");
        jmiCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadCursoActionPerformed(evt);
            }
        });
        jmCad.add(jmiCadCurso);

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmCad.add(jmiSair);

        bmPrincipal.add(jmCad);

        jmPessoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jmPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/add-usuario.gif"))); // NOI18N
        jmPessoa.setText("Pessoas");

        jmiConsultarPess.setText("<html>Consultar<br>Pessoas");
        jmiConsultarPess.setActionCommand("Consultar Pessoas");
        jmiConsultarPess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarPessActionPerformed(evt);
            }
        });
        jmPessoa.add(jmiConsultarPess);

        jmiCadPess.setText("<html>Cadastrar<br>Pessoas");
        jmiCadPess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadPessActionPerformed(evt);
            }
        });
        jmPessoa.add(jmiCadPess);

        bmPrincipal.add(jmPessoa);

        jmQT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jmQT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/questao-icone(3).jpg"))); // NOI18N
        jmQT.setText("Questões");

        jmiConsulQT.setText("<html>Consultar<br>Questões");
        jmiConsulQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsulQTActionPerformed(evt);
            }
        });
        jmQT.add(jmiConsulQT);

        jmiCadQT.setText("<html>Cadastrar<br>Questões");
        jmiCadQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadQTActionPerformed(evt);
            }
        });
        jmQT.add(jmiCadQT);

        bmPrincipal.add(jmQT);

        jmAvaliacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jmAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/avaliacao - 2.0.gif"))); // NOI18N
        jmAvaliacao.setText("Avaliações");

        jmiConsulAval.setText("<html>Consultar<br>Avaliações");
        jmAvaliacao.add(jmiConsulAval);

        jmiMontarAval.setText("<html>Montar<br>Avaliação");
        jmAvaliacao.add(jmiMontarAval);

        bmPrincipal.add(jmAvaliacao);

        jmAjuda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jmAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/help.png"))); // NOI18N
        jmAjuda.setText("Ajuda");

        jmiSobre.setText("Sobre");
        jmAjuda.add(jmiSobre);

        bmPrincipal.add(jmAjuda);

        setJMenuBar(bmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadPessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadPessActionPerformed
        JICadPessoa cadpes = new JICadPessoa();
        cadpes.setVisible(true);
        pnPrincipal.add(cadpes);
        
        
        //pnPrincipal.add(new JICadPessoa()).setVisible(true);
    }//GEN-LAST:event_jmiCadPessActionPerformed

    private void jmiConsulQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsulQTActionPerformed
        pnPrincipal.add(new JIBuscaQT()).setVisible(true);
    }//GEN-LAST:event_jmiConsulQTActionPerformed

    private void jmiCadQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadQTActionPerformed
        pnPrincipal.add(new JICadastroQT()).setVisible(true);
    }//GEN-LAST:event_jmiCadQTActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        
        int resp = JOptionPane.showConfirmDialog(this, "Deseja sair do Sistema?", "Saindo...", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiCadDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadDisciplinaActionPerformed
        pnPrincipal.add(new JICadDisciplina()).setVisible(true);
    }//GEN-LAST:event_jmiCadDisciplinaActionPerformed

    private void jmiCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadCursoActionPerformed
        pnPrincipal.add(new JICadCurso()).setVisible(true);
    }//GEN-LAST:event_jmiCadCursoActionPerformed

    private void jmiConsultarPessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarPessActionPerformed
        pnPrincipal.add( new JIBuscaPessoa()).setVisible(true);
    }//GEN-LAST:event_jmiConsultarPessActionPerformed
    
    public void acessarCad(){
        
       // jmiCadPessActionPerformed(evt);
        JICadPessoa cadpes = new JICadPessoa();
        cadpes.setVisible(true);
        pnPrincipal.add(cadpes);
        
//pnPrincipal.add(new JICadPessoa()).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bmPrincipal;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmAvaliacao;
    public javax.swing.JMenu jmCad;
    public javax.swing.JMenu jmPessoa;
    private javax.swing.JMenu jmQT;
    private javax.swing.JMenuItem jmiCadCurso;
    private javax.swing.JMenuItem jmiCadDisciplina;
    public javax.swing.JMenuItem jmiCadPess;
    private javax.swing.JMenuItem jmiCadQT;
    private javax.swing.JMenuItem jmiConsulAval;
    private javax.swing.JMenuItem jmiConsulQT;
    public javax.swing.JMenuItem jmiConsultarPess;
    private javax.swing.JMenuItem jmiMontarAval;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    public javax.swing.JDesktopPane pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
